# Sections and Groups for YC application builder.

GROUPS = [
    {"id": "basics", "label": "Basics", "icon": "📋"},
    {"id": "idea", "label": "Your Idea", "icon": "💡"},
    {"id": "market", "label": "Market", "icon": "📊"},
    {"id": "traction", "label": "Traction", "icon": "🚀"},
    {"id": "team", "label": "Team", "icon": "👥"},
    {"id": "video", "label": "Video & Demo", "icon": "🎬"},
]

SECTIONS = [
    {
        "id": "company_name",
        "group": "basics",
        "question": "Company name",
        "prefill": "",
        "tips": ["Use the legal or product name you'll use in the application."],
        "coaching": "Keep it short and recognizable.",
    },
    {
        "id": "one_liner",
        "group": "idea",
        "question": "Describe what your company does in 50 characters or less.",
        "prefill": "",
        "tips": ["Clear, specific, no jargon. What do you build and for whom?"],
        "coaching": "Imagine explaining it to a smart friend in one sentence.",
    },
    {
        "id": "what_problem",
        "group": "idea",
        "question": "What is the problem you're solving?",
        "prefill": "",
        "tips": ["Be specific about who has this problem and why it's painful."],
        "coaching": "Start with the pain, not your solution.",
    },
    {
        "id": "solution",
        "group": "idea",
        "question": "What is your solution?",
        "prefill": "",
        "tips": ["Explain it simply. Avoid buzzwords."],
        "coaching": "What does the user actually do with your product?",
    },
    {
        "id": "why_now",
        "group": "idea",
        "question": "Why now? What has changed recently that makes this possible?",
        "prefill": "",
        "tips": ["New technology, regulation, market shift, or behavior change."],
        "coaching": "The best startups ride a wave. What's yours?",
    },
    {
        "id": "market_size",
        "group": "market",
        "question": "How big is the market? (TAM)",
        "prefill": "",
        "tips": ["Use credible sources. Top-down AND bottom-up."],
        "coaching": "Show you've thought about the real opportunity, not just a TAM slide.",
    },
    {
        "id": "competitors",
        "group": "market",
        "question": "Who are your competitors? What do you understand that they don't?",
        "prefill": "",
        "tips": ["Never say 'no competitors'. Name them and explain your edge."],
        "coaching": "Insight > feature list. What do YOU see that others miss?",
    },
    {
        "id": "traction",
        "group": "traction",
        "question": "What traction do you have? (Revenue, users, growth rate)",
        "prefill": "",
        "tips": ["Be concrete: $X MRR, Y users, Z% weekly growth."],
        "coaching": "Numbers beat adjectives. Even small numbers show execution.",
    },
    {
        "id": "how_make_money",
        "group": "traction",
        "question": "How do or will you make money?",
        "prefill": "",
        "tips": ["SaaS subscription, marketplace take rate, usage-based..."],
        "coaching": "Simple business models win. Show unit economics if you have them.",
    },
    {
        "id": "founders",
        "group": "team",
        "question": "Tell us about your founders. Why is this team uniquely positioned?",
        "prefill": "",
        "tips": ["Background, relevant experience, why THIS problem."],
        "coaching": "63% of YC teams are 2 founders. Domain expertise matters most.",
    },
    {
        "id": "how_met",
        "group": "team",
        "question": "How long have the founders known each other? How did you meet?",
        "prefill": "",
        "tips": ["YC values founder relationships that have been tested."],
        "coaching": "Long relationships signal lower breakup risk.",
    },
    {
        "id": "video",
        "group": "video",
        "question": "Video URL (1 min founder intro)",
        "prefill": "",
        "tips": ["Unlisted YouTube. You talking to camera, no slides, no edits."],
        "coaching": "Authentic and concise. Energy matters. Practice 3x, record on the 4th.",
    },
    {
        "id": "demo_url",
        "group": "video",
        "question": "Demo / product URL",
        "prefill": "",
        "tips": ["Working demo or link to try the product."],
        "coaching": "Make it easy for reviewers to experience your product in 30 seconds.",
    },
]
